# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b147cdc5d87585ac5cde7c9395cfe937e33dee3b852cc2686069630e26048e4ad816a35a94d3444c7e66ed5782d27d526c82ded23ff326c50c47ba76df12d81

test:
  secret_key_base: 797578b3ee1faf0c6722442b2b125711fb13425653d46cbb66b58d8efdb4d1c72a50d47fcd2adf292e79cc02e676883e85df1971a2392502d05f84512aeccc54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
